### ISSUE TITLE
Allow flake8@4

### ISSUE THREAD

**Issue by DmytroLitvinov** [xome4ok/flake8-new-union-types#1]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flake8-new-union-types 0.4.0 requires flake8<4.0.0,>=3.0.0, but you have flake8 4.0.1 which is incompatible.

We need to allow flake8@4 version in pyproject.toml file https://github.com/xome4ok/flake8-new-union-types/blob/2801c8a54291f98ddd255623e60ec1abcca71d0d/pyproject.toml#L42

**Comment by arseniiarsenii** [comment]
I ran into the same issue today. We need a version bump for the flake8 dependencies to allow usage of flake8 version 4 and up with this package.

Besides that, thank you for your work, great extension :+1: 

Error output (Poetry):
```
poetry add flake8-new-union-types
Using version ^0.4.0 for flake8-new-union-types

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because flake8-new-union-types (0.4.0) depends on flake8 (>=3.0.0,<4.0.0)
   and no versions of flake8-new-union-types match >0.4.0,<0.5.0, flake8-new-union-types (>=0.4.0,<0.5.0) requires flake8 (>=3.0.0,<4.0.0).
  So, because <project name> depends on both flake8-new-union-types (^0.4.0) and flake8 (^4.0.1), version solving failed.
```

**Comment by xome4ok** [comment]
Thank you for reporting this issue and providing details.
I've updated dependencies for the package and tested it. Works fine now, check it out :)
